services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: go-echo-huma
    restart: always
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    environment:
      PORT:
      API_BASE_PATH:
      JWT_SECRET:
      LOG_LEVEL:
      MONGO_HOST:
      MONGO_PORT:
      DB_NAME:
      DB_USER:
      DB_PASS:
      S3_ENDPOINT:
      S3_BUCKET:
      AWS_REGION:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      PETSTORE_URL:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
