services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: go-echo-huma
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT:
      API_BASE_PATH:
      MONGO_HOST:
      MONGO_PORT:
      MONGO_USER:
      MONGO_PASS:
      DB_NAME:
      DB_USER:
      DB_PASS:
      AWS_REGION:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      S3_ENDPOINT:
      S3_BUCKET:
      PETSTORE_URL:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
