// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookPageRepository creates a new instance of MockBookPageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookPageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookPageRepository {
	mock := &MockBookPageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookPageRepository is an autogenerated mock type for the BookPageRepository type
type MockBookPageRepository struct {
	mock.Mock
}

type MockBookPageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookPageRepository) EXPECT() *MockBookPageRepository_Expecter {
	return &MockBookPageRepository_Expecter{mock: &_m.Mock}
}

// CreateBookPage provides a mock function for the type MockBookPageRepository
func (_mock *MockBookPageRepository) CreateBookPage(ctx context.Context, bookPage *entity.BookPage) (string, error) {
	ret := _mock.Called(ctx, bookPage)

	if len(ret) == 0 {
		panic("no return value specified for CreateBookPage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.BookPage) (string, error)); ok {
		return returnFunc(ctx, bookPage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.BookPage) string); ok {
		r0 = returnFunc(ctx, bookPage)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.BookPage) error); ok {
		r1 = returnFunc(ctx, bookPage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageRepository_CreateBookPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBookPage'
type MockBookPageRepository_CreateBookPage_Call struct {
	*mock.Call
}

// CreateBookPage is a helper method to define mock.On call
//   - ctx context.Context
//   - bookPage *entity.BookPage
func (_e *MockBookPageRepository_Expecter) CreateBookPage(ctx interface{}, bookPage interface{}) *MockBookPageRepository_CreateBookPage_Call {
	return &MockBookPageRepository_CreateBookPage_Call{Call: _e.mock.On("CreateBookPage", ctx, bookPage)}
}

func (_c *MockBookPageRepository_CreateBookPage_Call) Run(run func(ctx context.Context, bookPage *entity.BookPage)) *MockBookPageRepository_CreateBookPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.BookPage
		if args[1] != nil {
			arg1 = args[1].(*entity.BookPage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookPageRepository_CreateBookPage_Call) Return(s string, err error) *MockBookPageRepository_CreateBookPage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBookPageRepository_CreateBookPage_Call) RunAndReturn(run func(ctx context.Context, bookPage *entity.BookPage) (string, error)) *MockBookPageRepository_CreateBookPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookPageByID provides a mock function for the type MockBookPageRepository
func (_mock *MockBookPageRepository) GetBookPageByID(ctx context.Context, id string) (entity.BookPage, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookPageByID")
	}

	var r0 entity.BookPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.BookPage, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.BookPage); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.BookPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageRepository_GetBookPageByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookPageByID'
type MockBookPageRepository_GetBookPageByID_Call struct {
	*mock.Call
}

// GetBookPageByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookPageRepository_Expecter) GetBookPageByID(ctx interface{}, id interface{}) *MockBookPageRepository_GetBookPageByID_Call {
	return &MockBookPageRepository_GetBookPageByID_Call{Call: _e.mock.On("GetBookPageByID", ctx, id)}
}

func (_c *MockBookPageRepository_GetBookPageByID_Call) Run(run func(ctx context.Context, id string)) *MockBookPageRepository_GetBookPageByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookPageRepository_GetBookPageByID_Call) Return(bookPage entity.BookPage, err error) *MockBookPageRepository_GetBookPageByID_Call {
	_c.Call.Return(bookPage, err)
	return _c
}

func (_c *MockBookPageRepository_GetBookPageByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entity.BookPage, error)) *MockBookPageRepository_GetBookPageByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookPagesByBookID provides a mock function for the type MockBookPageRepository
func (_mock *MockBookPageRepository) GetBookPagesByBookID(ctx context.Context, bookID string) ([]entity.BookPage, error) {
	ret := _mock.Called(ctx, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookPagesByBookID")
	}

	var r0 []entity.BookPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.BookPage, error)); ok {
		return returnFunc(ctx, bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.BookPage); ok {
		r0 = returnFunc(ctx, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BookPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageRepository_GetBookPagesByBookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookPagesByBookID'
type MockBookPageRepository_GetBookPagesByBookID_Call struct {
	*mock.Call
}

// GetBookPagesByBookID is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID string
func (_e *MockBookPageRepository_Expecter) GetBookPagesByBookID(ctx interface{}, bookID interface{}) *MockBookPageRepository_GetBookPagesByBookID_Call {
	return &MockBookPageRepository_GetBookPagesByBookID_Call{Call: _e.mock.On("GetBookPagesByBookID", ctx, bookID)}
}

func (_c *MockBookPageRepository_GetBookPagesByBookID_Call) Run(run func(ctx context.Context, bookID string)) *MockBookPageRepository_GetBookPagesByBookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookPageRepository_GetBookPagesByBookID_Call) Return(bookPages []entity.BookPage, err error) *MockBookPageRepository_GetBookPagesByBookID_Call {
	_c.Call.Return(bookPages, err)
	return _c
}

func (_c *MockBookPageRepository_GetBookPagesByBookID_Call) RunAndReturn(run func(ctx context.Context, bookID string) ([]entity.BookPage, error)) *MockBookPageRepository_GetBookPagesByBookID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookpagesAroundPageNumber provides a mock function for the type MockBookPageRepository
func (_mock *MockBookPageRepository) GetBookpagesAroundPageNumber(ctx context.Context, bookID string, centerPage int64, offset int64) ([]entity.BookPage, error) {
	ret := _mock.Called(ctx, bookID, centerPage, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBookpagesAroundPageNumber")
	}

	var r0 []entity.BookPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]entity.BookPage, error)); ok {
		return returnFunc(ctx, bookID, centerPage, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) []entity.BookPage); ok {
		r0 = returnFunc(ctx, bookID, centerPage, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BookPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, bookID, centerPage, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageRepository_GetBookpagesAroundPageNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookpagesAroundPageNumber'
type MockBookPageRepository_GetBookpagesAroundPageNumber_Call struct {
	*mock.Call
}

// GetBookpagesAroundPageNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID string
//   - centerPage int64
//   - offset int64
func (_e *MockBookPageRepository_Expecter) GetBookpagesAroundPageNumber(ctx interface{}, bookID interface{}, centerPage interface{}, offset interface{}) *MockBookPageRepository_GetBookpagesAroundPageNumber_Call {
	return &MockBookPageRepository_GetBookpagesAroundPageNumber_Call{Call: _e.mock.On("GetBookpagesAroundPageNumber", ctx, bookID, centerPage, offset)}
}

func (_c *MockBookPageRepository_GetBookpagesAroundPageNumber_Call) Run(run func(ctx context.Context, bookID string, centerPage int64, offset int64)) *MockBookPageRepository_GetBookpagesAroundPageNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookPageRepository_GetBookpagesAroundPageNumber_Call) Return(bookPages []entity.BookPage, err error) *MockBookPageRepository_GetBookpagesAroundPageNumber_Call {
	_c.Call.Return(bookPages, err)
	return _c
}

func (_c *MockBookPageRepository_GetBookpagesAroundPageNumber_Call) RunAndReturn(run func(ctx context.Context, bookID string, centerPage int64, offset int64) ([]entity.BookPage, error)) *MockBookPageRepository_GetBookpagesAroundPageNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookpagesByBookIDWithPagination provides a mock function for the type MockBookPageRepository
func (_mock *MockBookPageRepository) GetBookpagesByBookIDWithPagination(ctx context.Context, bookID string, pageSize int64, pageNumber int64) ([]entity.BookPage, error) {
	ret := _mock.Called(ctx, bookID, pageSize, pageNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetBookpagesByBookIDWithPagination")
	}

	var r0 []entity.BookPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]entity.BookPage, error)); ok {
		return returnFunc(ctx, bookID, pageSize, pageNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) []entity.BookPage); ok {
		r0 = returnFunc(ctx, bookID, pageSize, pageNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BookPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, bookID, pageSize, pageNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageRepository_GetBookpagesByBookIDWithPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookpagesByBookIDWithPagination'
type MockBookPageRepository_GetBookpagesByBookIDWithPagination_Call struct {
	*mock.Call
}

// GetBookpagesByBookIDWithPagination is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID string
//   - pageSize int64
//   - pageNumber int64
func (_e *MockBookPageRepository_Expecter) GetBookpagesByBookIDWithPagination(ctx interface{}, bookID interface{}, pageSize interface{}, pageNumber interface{}) *MockBookPageRepository_GetBookpagesByBookIDWithPagination_Call {
	return &MockBookPageRepository_GetBookpagesByBookIDWithPagination_Call{Call: _e.mock.On("GetBookpagesByBookIDWithPagination", ctx, bookID, pageSize, pageNumber)}
}

func (_c *MockBookPageRepository_GetBookpagesByBookIDWithPagination_Call) Run(run func(ctx context.Context, bookID string, pageSize int64, pageNumber int64)) *MockBookPageRepository_GetBookpagesByBookIDWithPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookPageRepository_GetBookpagesByBookIDWithPagination_Call) Return(bookPages []entity.BookPage, err error) *MockBookPageRepository_GetBookpagesByBookIDWithPagination_Call {
	_c.Call.Return(bookPages, err)
	return _c
}

func (_c *MockBookPageRepository_GetBookpagesByBookIDWithPagination_Call) RunAndReturn(run func(ctx context.Context, bookID string, pageSize int64, pageNumber int64) ([]entity.BookPage, error)) *MockBookPageRepository_GetBookpagesByBookIDWithPagination_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookpagesByPageRange provides a mock function for the type MockBookPageRepository
func (_mock *MockBookPageRepository) GetBookpagesByPageRange(ctx context.Context, bookID string, startPage int64, endPage int64) ([]entity.BookPage, error) {
	ret := _mock.Called(ctx, bookID, startPage, endPage)

	if len(ret) == 0 {
		panic("no return value specified for GetBookpagesByPageRange")
	}

	var r0 []entity.BookPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]entity.BookPage, error)); ok {
		return returnFunc(ctx, bookID, startPage, endPage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) []entity.BookPage); ok {
		r0 = returnFunc(ctx, bookID, startPage, endPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BookPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, bookID, startPage, endPage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageRepository_GetBookpagesByPageRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookpagesByPageRange'
type MockBookPageRepository_GetBookpagesByPageRange_Call struct {
	*mock.Call
}

// GetBookpagesByPageRange is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID string
//   - startPage int64
//   - endPage int64
func (_e *MockBookPageRepository_Expecter) GetBookpagesByPageRange(ctx interface{}, bookID interface{}, startPage interface{}, endPage interface{}) *MockBookPageRepository_GetBookpagesByPageRange_Call {
	return &MockBookPageRepository_GetBookpagesByPageRange_Call{Call: _e.mock.On("GetBookpagesByPageRange", ctx, bookID, startPage, endPage)}
}

func (_c *MockBookPageRepository_GetBookpagesByPageRange_Call) Run(run func(ctx context.Context, bookID string, startPage int64, endPage int64)) *MockBookPageRepository_GetBookpagesByPageRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookPageRepository_GetBookpagesByPageRange_Call) Return(bookPages []entity.BookPage, err error) *MockBookPageRepository_GetBookpagesByPageRange_Call {
	_c.Call.Return(bookPages, err)
	return _c
}

func (_c *MockBookPageRepository_GetBookpagesByPageRange_Call) RunAndReturn(run func(ctx context.Context, bookID string, startPage int64, endPage int64) ([]entity.BookPage, error)) *MockBookPageRepository_GetBookpagesByPageRange_Call {
	_c.Call.Return(run)
	return _c
}
