// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileRecordRepository creates a new instance of MockFileRecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileRecordRepository {
	mock := &MockFileRecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileRecordRepository is an autogenerated mock type for the FileRecordRepository type
type MockFileRecordRepository struct {
	mock.Mock
}

type MockFileRecordRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileRecordRepository) EXPECT() *MockFileRecordRepository_Expecter {
	return &MockFileRecordRepository_Expecter{mock: &_m.Mock}
}

// CreateFileRecord provides a mock function for the type MockFileRecordRepository
func (_mock *MockFileRecordRepository) CreateFileRecord(ctx context.Context, fileRecord *entity.FileRecord) (string, error) {
	ret := _mock.Called(ctx, fileRecord)

	if len(ret) == 0 {
		panic("no return value specified for CreateFileRecord")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.FileRecord) (string, error)); ok {
		return returnFunc(ctx, fileRecord)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.FileRecord) string); ok {
		r0 = returnFunc(ctx, fileRecord)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.FileRecord) error); ok {
		r1 = returnFunc(ctx, fileRecord)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRecordRepository_CreateFileRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFileRecord'
type MockFileRecordRepository_CreateFileRecord_Call struct {
	*mock.Call
}

// CreateFileRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - fileRecord *entity.FileRecord
func (_e *MockFileRecordRepository_Expecter) CreateFileRecord(ctx interface{}, fileRecord interface{}) *MockFileRecordRepository_CreateFileRecord_Call {
	return &MockFileRecordRepository_CreateFileRecord_Call{Call: _e.mock.On("CreateFileRecord", ctx, fileRecord)}
}

func (_c *MockFileRecordRepository_CreateFileRecord_Call) Run(run func(ctx context.Context, fileRecord *entity.FileRecord)) *MockFileRecordRepository_CreateFileRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.FileRecord
		if args[1] != nil {
			arg1 = args[1].(*entity.FileRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRecordRepository_CreateFileRecord_Call) Return(s string, err error) *MockFileRecordRepository_CreateFileRecord_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileRecordRepository_CreateFileRecord_Call) RunAndReturn(run func(ctx context.Context, fileRecord *entity.FileRecord) (string, error)) *MockFileRecordRepository_CreateFileRecord_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileRecordByID provides a mock function for the type MockFileRecordRepository
func (_mock *MockFileRecordRepository) GetFileRecordByID(ctx context.Context, fileID string) (entity.FileRecord, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileRecordByID")
	}

	var r0 entity.FileRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.FileRecord, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.FileRecord); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(entity.FileRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRecordRepository_GetFileRecordByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileRecordByID'
type MockFileRecordRepository_GetFileRecordByID_Call struct {
	*mock.Call
}

// GetFileRecordByID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockFileRecordRepository_Expecter) GetFileRecordByID(ctx interface{}, fileID interface{}) *MockFileRecordRepository_GetFileRecordByID_Call {
	return &MockFileRecordRepository_GetFileRecordByID_Call{Call: _e.mock.On("GetFileRecordByID", ctx, fileID)}
}

func (_c *MockFileRecordRepository_GetFileRecordByID_Call) Run(run func(ctx context.Context, fileID string)) *MockFileRecordRepository_GetFileRecordByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRecordRepository_GetFileRecordByID_Call) Return(fileRecord entity.FileRecord, err error) *MockFileRecordRepository_GetFileRecordByID_Call {
	_c.Call.Return(fileRecord, err)
	return _c
}

func (_c *MockFileRecordRepository_GetFileRecordByID_Call) RunAndReturn(run func(ctx context.Context, fileID string) (entity.FileRecord, error)) *MockFileRecordRepository_GetFileRecordByID_Call {
	_c.Call.Return(run)
	return _c
}
