// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileStorage creates a new instance of MockFileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileStorage {
	mock := &MockFileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileStorage is an autogenerated mock type for the FileStorage type
type MockFileStorage struct {
	mock.Mock
}

type MockFileStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileStorage) EXPECT() *MockFileStorage_Expecter {
	return &MockFileStorage_Expecter{mock: &_m.Mock}
}

// CheckFileExists provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) CheckFileExists(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for CheckFileExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStorage_CheckFileExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckFileExists'
type MockFileStorage_CheckFileExists_Call struct {
	*mock.Call
}

// CheckFileExists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFileStorage_Expecter) CheckFileExists(ctx interface{}, key interface{}) *MockFileStorage_CheckFileExists_Call {
	return &MockFileStorage_CheckFileExists_Call{Call: _e.mock.On("CheckFileExists", ctx, key)}
}

func (_c *MockFileStorage_CheckFileExists_Call) Run(run func(ctx context.Context, key string)) *MockFileStorage_CheckFileExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileStorage_CheckFileExists_Call) Return(b bool, err error) *MockFileStorage_CheckFileExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFileStorage_CheckFileExists_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockFileStorage_CheckFileExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignedDownloadURL provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) GetPresignedDownloadURL(ctx context.Context, key string, filename string, duration time.Duration) (string, error) {
	ret := _mock.Called(ctx, key, filename, duration)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedDownloadURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (string, error)); ok {
		return returnFunc(ctx, key, filename, duration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) string); ok {
		r0 = returnFunc(ctx, key, filename, duration)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, filename, duration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStorage_GetPresignedDownloadURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedDownloadURL'
type MockFileStorage_GetPresignedDownloadURL_Call struct {
	*mock.Call
}

// GetPresignedDownloadURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - filename string
//   - duration time.Duration
func (_e *MockFileStorage_Expecter) GetPresignedDownloadURL(ctx interface{}, key interface{}, filename interface{}, duration interface{}) *MockFileStorage_GetPresignedDownloadURL_Call {
	return &MockFileStorage_GetPresignedDownloadURL_Call{Call: _e.mock.On("GetPresignedDownloadURL", ctx, key, filename, duration)}
}

func (_c *MockFileStorage_GetPresignedDownloadURL_Call) Run(run func(ctx context.Context, key string, filename string, duration time.Duration)) *MockFileStorage_GetPresignedDownloadURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFileStorage_GetPresignedDownloadURL_Call) Return(s string, err error) *MockFileStorage_GetPresignedDownloadURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileStorage_GetPresignedDownloadURL_Call) RunAndReturn(run func(ctx context.Context, key string, filename string, duration time.Duration) (string, error)) *MockFileStorage_GetPresignedDownloadURL_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiles provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) ListFiles(ctx context.Context, maxKeys int) ([]string, error) {
	ret := _mock.Called(ctx, maxKeys)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return returnFunc(ctx, maxKeys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = returnFunc(ctx, maxKeys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, maxKeys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStorage_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type MockFileStorage_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - maxKeys int
func (_e *MockFileStorage_Expecter) ListFiles(ctx interface{}, maxKeys interface{}) *MockFileStorage_ListFiles_Call {
	return &MockFileStorage_ListFiles_Call{Call: _e.mock.On("ListFiles", ctx, maxKeys)}
}

func (_c *MockFileStorage_ListFiles_Call) Run(run func(ctx context.Context, maxKeys int)) *MockFileStorage_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileStorage_ListFiles_Call) Return(strings []string, err error) *MockFileStorage_ListFiles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockFileStorage_ListFiles_Call) RunAndReturn(run func(ctx context.Context, maxKeys int) ([]string, error)) *MockFileStorage_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) UploadFile(ctx context.Context, key string, file io.Reader, size int64, contentType string) error {
	ret := _mock.Called(ctx, key, file, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r0 = returnFunc(ctx, key, file, size, contentType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileStorage_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type MockFileStorage_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - file io.Reader
//   - size int64
//   - contentType string
func (_e *MockFileStorage_Expecter) UploadFile(ctx interface{}, key interface{}, file interface{}, size interface{}, contentType interface{}) *MockFileStorage_UploadFile_Call {
	return &MockFileStorage_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, key, file, size, contentType)}
}

func (_c *MockFileStorage_UploadFile_Call) Run(run func(ctx context.Context, key string, file io.Reader, size int64, contentType string)) *MockFileStorage_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockFileStorage_UploadFile_Call) Return(err error) *MockFileStorage_UploadFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileStorage_UploadFile_Call) RunAndReturn(run func(ctx context.Context, key string, file io.Reader, size int64, contentType string) error) *MockFileStorage_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}
