// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPetService creates a new instance of MockPetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPetService {
	mock := &MockPetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPetService is an autogenerated mock type for the PetService type
type MockPetService struct {
	mock.Mock
}

type MockPetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPetService) EXPECT() *MockPetService_Expecter {
	return &MockPetService_Expecter{mock: &_m.Mock}
}

// GetPetByID provides a mock function for the type MockPetService
func (_mock *MockPetService) GetPetByID(ctx context.Context, id int64) (entity.Pet, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPetByID")
	}

	var r0 entity.Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (entity.Pet, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) entity.Pet); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Pet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetService_GetPetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPetByID'
type MockPetService_GetPetByID_Call struct {
	*mock.Call
}

// GetPetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockPetService_Expecter) GetPetByID(ctx interface{}, id interface{}) *MockPetService_GetPetByID_Call {
	return &MockPetService_GetPetByID_Call{Call: _e.mock.On("GetPetByID", ctx, id)}
}

func (_c *MockPetService_GetPetByID_Call) Run(run func(ctx context.Context, id int64)) *MockPetService_GetPetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetService_GetPetByID_Call) Return(pet entity.Pet, err error) *MockPetService_GetPetByID_Call {
	_c.Call.Return(pet, err)
	return _c
}

func (_c *MockPetService_GetPetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (entity.Pet, error)) *MockPetService_GetPetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPetsByStatus provides a mock function for the type MockPetService
func (_mock *MockPetService) GetPetsByStatus(ctx context.Context, status entity.PetStatus) ([]entity.Pet, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for GetPetsByStatus")
	}

	var r0 []entity.Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.PetStatus) ([]entity.Pet, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.PetStatus) []entity.Pet); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.PetStatus) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetService_GetPetsByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPetsByStatus'
type MockPetService_GetPetsByStatus_Call struct {
	*mock.Call
}

// GetPetsByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status entity.PetStatus
func (_e *MockPetService_Expecter) GetPetsByStatus(ctx interface{}, status interface{}) *MockPetService_GetPetsByStatus_Call {
	return &MockPetService_GetPetsByStatus_Call{Call: _e.mock.On("GetPetsByStatus", ctx, status)}
}

func (_c *MockPetService_GetPetsByStatus_Call) Run(run func(ctx context.Context, status entity.PetStatus)) *MockPetService_GetPetsByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.PetStatus
		if args[1] != nil {
			arg1 = args[1].(entity.PetStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetService_GetPetsByStatus_Call) Return(pets []entity.Pet, err error) *MockPetService_GetPetsByStatus_Call {
	_c.Call.Return(pets, err)
	return _c
}

func (_c *MockPetService_GetPetsByStatus_Call) RunAndReturn(run func(ctx context.Context, status entity.PetStatus) ([]entity.Pet, error)) *MockPetService_GetPetsByStatus_Call {
	_c.Call.Return(run)
	return _c
}
