// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReviewRepository creates a new instance of MockReviewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewRepository {
	mock := &MockReviewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewRepository is an autogenerated mock type for the ReviewRepository type
type MockReviewRepository struct {
	mock.Mock
}

type MockReviewRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewRepository) EXPECT() *MockReviewRepository_Expecter {
	return &MockReviewRepository_Expecter{mock: &_m.Mock}
}

// CreateReview provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) CreateReview(ctx context.Context, review *entity.Review) error {
	ret := _mock.Called(ctx, review)

	if len(ret) == 0 {
		panic("no return value specified for CreateReview")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Review) error); ok {
		r0 = returnFunc(ctx, review)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewRepository_CreateReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReview'
type MockReviewRepository_CreateReview_Call struct {
	*mock.Call
}

// CreateReview is a helper method to define mock.On call
//   - ctx context.Context
//   - review *entity.Review
func (_e *MockReviewRepository_Expecter) CreateReview(ctx interface{}, review interface{}) *MockReviewRepository_CreateReview_Call {
	return &MockReviewRepository_CreateReview_Call{Call: _e.mock.On("CreateReview", ctx, review)}
}

func (_c *MockReviewRepository_CreateReview_Call) Run(run func(ctx context.Context, review *entity.Review)) *MockReviewRepository_CreateReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Review
		if args[1] != nil {
			arg1 = args[1].(*entity.Review)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewRepository_CreateReview_Call) Return(err error) *MockReviewRepository_CreateReview_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewRepository_CreateReview_Call) RunAndReturn(run func(ctx context.Context, review *entity.Review) error) *MockReviewRepository_CreateReview_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviews provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) GetReviews(ctx context.Context, limit int64) ([]entity.Review, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetReviews")
	}

	var r0 []entity.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]entity.Review, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []entity.Review); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewRepository_GetReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviews'
type MockReviewRepository_GetReviews_Call struct {
	*mock.Call
}

// GetReviews is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
func (_e *MockReviewRepository_Expecter) GetReviews(ctx interface{}, limit interface{}) *MockReviewRepository_GetReviews_Call {
	return &MockReviewRepository_GetReviews_Call{Call: _e.mock.On("GetReviews", ctx, limit)}
}

func (_c *MockReviewRepository_GetReviews_Call) Run(run func(ctx context.Context, limit int64)) *MockReviewRepository_GetReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewRepository_GetReviews_Call) Return(reviews []entity.Review, err error) *MockReviewRepository_GetReviews_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewRepository_GetReviews_Call) RunAndReturn(run func(ctx context.Context, limit int64) ([]entity.Review, error)) *MockReviewRepository_GetReviews_Call {
	_c.Call.Return(run)
	return _c
}
