// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/utility/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenUtility creates a new instance of MockTokenUtility. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenUtility(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenUtility {
	mock := &MockTokenUtility{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenUtility is an autogenerated mock type for the TokenUtility type
type MockTokenUtility struct {
	mock.Mock
}

type MockTokenUtility_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenUtility) EXPECT() *MockTokenUtility_Expecter {
	return &MockTokenUtility_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function for the type MockTokenUtility
func (_mock *MockTokenUtility) GenerateToken(userID string, role string) (string, error) {
	ret := _mock.Called(userID, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(userID, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenUtility_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockTokenUtility_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - userID string
//   - role string
func (_e *MockTokenUtility_Expecter) GenerateToken(userID interface{}, role interface{}) *MockTokenUtility_GenerateToken_Call {
	return &MockTokenUtility_GenerateToken_Call{Call: _e.mock.On("GenerateToken", userID, role)}
}

func (_c *MockTokenUtility_GenerateToken_Call) Run(run func(userID string, role string)) *MockTokenUtility_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenUtility_GenerateToken_Call) Return(s string, err error) *MockTokenUtility_GenerateToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenUtility_GenerateToken_Call) RunAndReturn(run func(userID string, role string) (string, error)) *MockTokenUtility_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToken provides a mock function for the type MockTokenUtility
func (_mock *MockTokenUtility) ParseToken(token string) (auth.AuthContext, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 auth.AuthContext
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (auth.AuthContext, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) auth.AuthContext); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(auth.AuthContext)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenUtility_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type MockTokenUtility_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenUtility_Expecter) ParseToken(token interface{}) *MockTokenUtility_ParseToken_Call {
	return &MockTokenUtility_ParseToken_Call{Call: _e.mock.On("ParseToken", token)}
}

func (_c *MockTokenUtility_ParseToken_Call) Run(run func(token string)) *MockTokenUtility_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenUtility_ParseToken_Call) Return(authContext auth.AuthContext, err error) *MockTokenUtility_ParseToken_Call {
	_c.Call.Return(authContext, err)
	return _c
}

func (_c *MockTokenUtility_ParseToken_Call) RunAndReturn(run func(token string) (auth.AuthContext, error)) *MockTokenUtility_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}
