// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookUseCase creates a new instance of MockBookUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookUseCase {
	mock := &MockBookUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookUseCase is an autogenerated mock type for the BookUseCase type
type MockBookUseCase struct {
	mock.Mock
}

type MockBookUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookUseCase) EXPECT() *MockBookUseCase_Expecter {
	return &MockBookUseCase_Expecter{mock: &_m.Mock}
}

// CreateBook provides a mock function for the type MockBookUseCase
func (_mock *MockBookUseCase) CreateBook(ctx context.Context, book *entity.Book) (string, error) {
	ret := _mock.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for CreateBook")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Book) (string, error)); ok {
		return returnFunc(ctx, book)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Book) string); ok {
		r0 = returnFunc(ctx, book)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Book) error); ok {
		r1 = returnFunc(ctx, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookUseCase_CreateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBook'
type MockBookUseCase_CreateBook_Call struct {
	*mock.Call
}

// CreateBook is a helper method to define mock.On call
//   - ctx context.Context
//   - book *entity.Book
func (_e *MockBookUseCase_Expecter) CreateBook(ctx interface{}, book interface{}) *MockBookUseCase_CreateBook_Call {
	return &MockBookUseCase_CreateBook_Call{Call: _e.mock.On("CreateBook", ctx, book)}
}

func (_c *MockBookUseCase_CreateBook_Call) Run(run func(ctx context.Context, book *entity.Book)) *MockBookUseCase_CreateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Book
		if args[1] != nil {
			arg1 = args[1].(*entity.Book)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookUseCase_CreateBook_Call) Return(s string, err error) *MockBookUseCase_CreateBook_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBookUseCase_CreateBook_Call) RunAndReturn(run func(ctx context.Context, book *entity.Book) (string, error)) *MockBookUseCase_CreateBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBooks provides a mock function for the type MockBookUseCase
func (_mock *MockBookUseCase) GetAllBooks(ctx context.Context) ([]entity.Book, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBooks")
	}

	var r0 []entity.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.Book, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.Book); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookUseCase_GetAllBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBooks'
type MockBookUseCase_GetAllBooks_Call struct {
	*mock.Call
}

// GetAllBooks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBookUseCase_Expecter) GetAllBooks(ctx interface{}) *MockBookUseCase_GetAllBooks_Call {
	return &MockBookUseCase_GetAllBooks_Call{Call: _e.mock.On("GetAllBooks", ctx)}
}

func (_c *MockBookUseCase_GetAllBooks_Call) Run(run func(ctx context.Context)) *MockBookUseCase_GetAllBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookUseCase_GetAllBooks_Call) Return(books []entity.Book, err error) *MockBookUseCase_GetAllBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockBookUseCase_GetAllBooks_Call) RunAndReturn(run func(ctx context.Context) ([]entity.Book, error)) *MockBookUseCase_GetAllBooks_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByID provides a mock function for the type MockBookUseCase
func (_mock *MockBookUseCase) GetBookByID(ctx context.Context, id string) (entity.Book, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByID")
	}

	var r0 entity.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.Book, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.Book); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookUseCase_GetBookByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByID'
type MockBookUseCase_GetBookByID_Call struct {
	*mock.Call
}

// GetBookByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookUseCase_Expecter) GetBookByID(ctx interface{}, id interface{}) *MockBookUseCase_GetBookByID_Call {
	return &MockBookUseCase_GetBookByID_Call{Call: _e.mock.On("GetBookByID", ctx, id)}
}

func (_c *MockBookUseCase_GetBookByID_Call) Run(run func(ctx context.Context, id string)) *MockBookUseCase_GetBookByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookUseCase_GetBookByID_Call) Return(book entity.Book, err error) *MockBookUseCase_GetBookByID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockBookUseCase_GetBookByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entity.Book, error)) *MockBookUseCase_GetBookByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksWithPagination provides a mock function for the type MockBookUseCase
func (_mock *MockBookUseCase) GetBooksWithPagination(ctx context.Context, pageSize int64, pageNumber int64) ([]entity.Book, error) {
	ret := _mock.Called(ctx, pageSize, pageNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksWithPagination")
	}

	var r0 []entity.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) ([]entity.Book, error)); ok {
		return returnFunc(ctx, pageSize, pageNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) []entity.Book); ok {
		r0 = returnFunc(ctx, pageSize, pageNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, pageSize, pageNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookUseCase_GetBooksWithPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksWithPagination'
type MockBookUseCase_GetBooksWithPagination_Call struct {
	*mock.Call
}

// GetBooksWithPagination is a helper method to define mock.On call
//   - ctx context.Context
//   - pageSize int64
//   - pageNumber int64
func (_e *MockBookUseCase_Expecter) GetBooksWithPagination(ctx interface{}, pageSize interface{}, pageNumber interface{}) *MockBookUseCase_GetBooksWithPagination_Call {
	return &MockBookUseCase_GetBooksWithPagination_Call{Call: _e.mock.On("GetBooksWithPagination", ctx, pageSize, pageNumber)}
}

func (_c *MockBookUseCase_GetBooksWithPagination_Call) Run(run func(ctx context.Context, pageSize int64, pageNumber int64)) *MockBookUseCase_GetBooksWithPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookUseCase_GetBooksWithPagination_Call) Return(books []entity.Book, err error) *MockBookUseCase_GetBooksWithPagination_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockBookUseCase_GetBooksWithPagination_Call) RunAndReturn(run func(ctx context.Context, pageSize int64, pageNumber int64) ([]entity.Book, error)) *MockBookUseCase_GetBooksWithPagination_Call {
	_c.Call.Return(run)
	return _c
}
