// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookPageUseCase creates a new instance of MockBookPageUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookPageUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookPageUseCase {
	mock := &MockBookPageUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookPageUseCase is an autogenerated mock type for the BookPageUseCase type
type MockBookPageUseCase struct {
	mock.Mock
}

type MockBookPageUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookPageUseCase) EXPECT() *MockBookPageUseCase_Expecter {
	return &MockBookPageUseCase_Expecter{mock: &_m.Mock}
}

// CreateBookPage provides a mock function for the type MockBookPageUseCase
func (_mock *MockBookPageUseCase) CreateBookPage(ctx context.Context, bookPage *entity.BookPage) (string, error) {
	ret := _mock.Called(ctx, bookPage)

	if len(ret) == 0 {
		panic("no return value specified for CreateBookPage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.BookPage) (string, error)); ok {
		return returnFunc(ctx, bookPage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.BookPage) string); ok {
		r0 = returnFunc(ctx, bookPage)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.BookPage) error); ok {
		r1 = returnFunc(ctx, bookPage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageUseCase_CreateBookPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBookPage'
type MockBookPageUseCase_CreateBookPage_Call struct {
	*mock.Call
}

// CreateBookPage is a helper method to define mock.On call
//   - ctx context.Context
//   - bookPage *entity.BookPage
func (_e *MockBookPageUseCase_Expecter) CreateBookPage(ctx interface{}, bookPage interface{}) *MockBookPageUseCase_CreateBookPage_Call {
	return &MockBookPageUseCase_CreateBookPage_Call{Call: _e.mock.On("CreateBookPage", ctx, bookPage)}
}

func (_c *MockBookPageUseCase_CreateBookPage_Call) Run(run func(ctx context.Context, bookPage *entity.BookPage)) *MockBookPageUseCase_CreateBookPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.BookPage
		if args[1] != nil {
			arg1 = args[1].(*entity.BookPage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookPageUseCase_CreateBookPage_Call) Return(s string, err error) *MockBookPageUseCase_CreateBookPage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBookPageUseCase_CreateBookPage_Call) RunAndReturn(run func(ctx context.Context, bookPage *entity.BookPage) (string, error)) *MockBookPageUseCase_CreateBookPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBookPages provides a mock function for the type MockBookPageUseCase
func (_mock *MockBookPageUseCase) GetAllBookPages(ctx context.Context, bookID string) ([]entity.BookPage, error) {
	ret := _mock.Called(ctx, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBookPages")
	}

	var r0 []entity.BookPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.BookPage, error)); ok {
		return returnFunc(ctx, bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.BookPage); ok {
		r0 = returnFunc(ctx, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BookPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageUseCase_GetAllBookPages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBookPages'
type MockBookPageUseCase_GetAllBookPages_Call struct {
	*mock.Call
}

// GetAllBookPages is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID string
func (_e *MockBookPageUseCase_Expecter) GetAllBookPages(ctx interface{}, bookID interface{}) *MockBookPageUseCase_GetAllBookPages_Call {
	return &MockBookPageUseCase_GetAllBookPages_Call{Call: _e.mock.On("GetAllBookPages", ctx, bookID)}
}

func (_c *MockBookPageUseCase_GetAllBookPages_Call) Run(run func(ctx context.Context, bookID string)) *MockBookPageUseCase_GetAllBookPages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookPageUseCase_GetAllBookPages_Call) Return(bookPages []entity.BookPage, err error) *MockBookPageUseCase_GetAllBookPages_Call {
	_c.Call.Return(bookPages, err)
	return _c
}

func (_c *MockBookPageUseCase_GetAllBookPages_Call) RunAndReturn(run func(ctx context.Context, bookID string) ([]entity.BookPage, error)) *MockBookPageUseCase_GetAllBookPages_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookPageByID provides a mock function for the type MockBookPageUseCase
func (_mock *MockBookPageUseCase) GetBookPageByID(ctx context.Context, id string) (entity.BookPage, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookPageByID")
	}

	var r0 entity.BookPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.BookPage, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.BookPage); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.BookPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageUseCase_GetBookPageByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookPageByID'
type MockBookPageUseCase_GetBookPageByID_Call struct {
	*mock.Call
}

// GetBookPageByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookPageUseCase_Expecter) GetBookPageByID(ctx interface{}, id interface{}) *MockBookPageUseCase_GetBookPageByID_Call {
	return &MockBookPageUseCase_GetBookPageByID_Call{Call: _e.mock.On("GetBookPageByID", ctx, id)}
}

func (_c *MockBookPageUseCase_GetBookPageByID_Call) Run(run func(ctx context.Context, id string)) *MockBookPageUseCase_GetBookPageByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookPageUseCase_GetBookPageByID_Call) Return(bookPage entity.BookPage, err error) *MockBookPageUseCase_GetBookPageByID_Call {
	_c.Call.Return(bookPage, err)
	return _c
}

func (_c *MockBookPageUseCase_GetBookPageByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entity.BookPage, error)) *MockBookPageUseCase_GetBookPageByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookPagesByOffset provides a mock function for the type MockBookPageUseCase
func (_mock *MockBookPageUseCase) GetBookPagesByOffset(ctx context.Context, bookID string, centerPage int64, offset int64) ([]entity.BookPage, error) {
	ret := _mock.Called(ctx, bookID, centerPage, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBookPagesByOffset")
	}

	var r0 []entity.BookPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]entity.BookPage, error)); ok {
		return returnFunc(ctx, bookID, centerPage, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) []entity.BookPage); ok {
		r0 = returnFunc(ctx, bookID, centerPage, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BookPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, bookID, centerPage, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageUseCase_GetBookPagesByOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookPagesByOffset'
type MockBookPageUseCase_GetBookPagesByOffset_Call struct {
	*mock.Call
}

// GetBookPagesByOffset is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID string
//   - centerPage int64
//   - offset int64
func (_e *MockBookPageUseCase_Expecter) GetBookPagesByOffset(ctx interface{}, bookID interface{}, centerPage interface{}, offset interface{}) *MockBookPageUseCase_GetBookPagesByOffset_Call {
	return &MockBookPageUseCase_GetBookPagesByOffset_Call{Call: _e.mock.On("GetBookPagesByOffset", ctx, bookID, centerPage, offset)}
}

func (_c *MockBookPageUseCase_GetBookPagesByOffset_Call) Run(run func(ctx context.Context, bookID string, centerPage int64, offset int64)) *MockBookPageUseCase_GetBookPagesByOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookPageUseCase_GetBookPagesByOffset_Call) Return(bookPages []entity.BookPage, err error) *MockBookPageUseCase_GetBookPagesByOffset_Call {
	_c.Call.Return(bookPages, err)
	return _c
}

func (_c *MockBookPageUseCase_GetBookPagesByOffset_Call) RunAndReturn(run func(ctx context.Context, bookID string, centerPage int64, offset int64) ([]entity.BookPage, error)) *MockBookPageUseCase_GetBookPagesByOffset_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookPagesByRange provides a mock function for the type MockBookPageUseCase
func (_mock *MockBookPageUseCase) GetBookPagesByRange(ctx context.Context, bookID string, startPage int64, endPage int64) ([]entity.BookPage, error) {
	ret := _mock.Called(ctx, bookID, startPage, endPage)

	if len(ret) == 0 {
		panic("no return value specified for GetBookPagesByRange")
	}

	var r0 []entity.BookPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]entity.BookPage, error)); ok {
		return returnFunc(ctx, bookID, startPage, endPage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) []entity.BookPage); ok {
		r0 = returnFunc(ctx, bookID, startPage, endPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BookPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, bookID, startPage, endPage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageUseCase_GetBookPagesByRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookPagesByRange'
type MockBookPageUseCase_GetBookPagesByRange_Call struct {
	*mock.Call
}

// GetBookPagesByRange is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID string
//   - startPage int64
//   - endPage int64
func (_e *MockBookPageUseCase_Expecter) GetBookPagesByRange(ctx interface{}, bookID interface{}, startPage interface{}, endPage interface{}) *MockBookPageUseCase_GetBookPagesByRange_Call {
	return &MockBookPageUseCase_GetBookPagesByRange_Call{Call: _e.mock.On("GetBookPagesByRange", ctx, bookID, startPage, endPage)}
}

func (_c *MockBookPageUseCase_GetBookPagesByRange_Call) Run(run func(ctx context.Context, bookID string, startPage int64, endPage int64)) *MockBookPageUseCase_GetBookPagesByRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookPageUseCase_GetBookPagesByRange_Call) Return(bookPages []entity.BookPage, err error) *MockBookPageUseCase_GetBookPagesByRange_Call {
	_c.Call.Return(bookPages, err)
	return _c
}

func (_c *MockBookPageUseCase_GetBookPagesByRange_Call) RunAndReturn(run func(ctx context.Context, bookID string, startPage int64, endPage int64) ([]entity.BookPage, error)) *MockBookPageUseCase_GetBookPagesByRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookPagesWithPagination provides a mock function for the type MockBookPageUseCase
func (_mock *MockBookPageUseCase) GetBookPagesWithPagination(ctx context.Context, bookID string, pageSize int64, pageNumber int64) ([]entity.BookPage, error) {
	ret := _mock.Called(ctx, bookID, pageSize, pageNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetBookPagesWithPagination")
	}

	var r0 []entity.BookPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]entity.BookPage, error)); ok {
		return returnFunc(ctx, bookID, pageSize, pageNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) []entity.BookPage); ok {
		r0 = returnFunc(ctx, bookID, pageSize, pageNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BookPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, bookID, pageSize, pageNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageUseCase_GetBookPagesWithPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookPagesWithPagination'
type MockBookPageUseCase_GetBookPagesWithPagination_Call struct {
	*mock.Call
}

// GetBookPagesWithPagination is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID string
//   - pageSize int64
//   - pageNumber int64
func (_e *MockBookPageUseCase_Expecter) GetBookPagesWithPagination(ctx interface{}, bookID interface{}, pageSize interface{}, pageNumber interface{}) *MockBookPageUseCase_GetBookPagesWithPagination_Call {
	return &MockBookPageUseCase_GetBookPagesWithPagination_Call{Call: _e.mock.On("GetBookPagesWithPagination", ctx, bookID, pageSize, pageNumber)}
}

func (_c *MockBookPageUseCase_GetBookPagesWithPagination_Call) Run(run func(ctx context.Context, bookID string, pageSize int64, pageNumber int64)) *MockBookPageUseCase_GetBookPagesWithPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookPageUseCase_GetBookPagesWithPagination_Call) Return(bookPages []entity.BookPage, err error) *MockBookPageUseCase_GetBookPagesWithPagination_Call {
	_c.Call.Return(bookPages, err)
	return _c
}

func (_c *MockBookPageUseCase_GetBookPagesWithPagination_Call) RunAndReturn(run func(ctx context.Context, bookID string, pageSize int64, pageNumber int64) ([]entity.BookPage, error)) *MockBookPageUseCase_GetBookPagesWithPagination_Call {
	_c.Call.Return(run)
	return _c
}
