// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileUseCase creates a new instance of MockFileUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileUseCase {
	mock := &MockFileUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileUseCase is an autogenerated mock type for the FileUseCase type
type MockFileUseCase struct {
	mock.Mock
}

type MockFileUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileUseCase) EXPECT() *MockFileUseCase_Expecter {
	return &MockFileUseCase_Expecter{mock: &_m.Mock}
}

// GetFileDownloadLink provides a mock function for the type MockFileUseCase
func (_mock *MockFileUseCase) GetFileDownloadLink(ctx context.Context, fileID string) (entity.FileDownloadInfo, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileDownloadLink")
	}

	var r0 entity.FileDownloadInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.FileDownloadInfo, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.FileDownloadInfo); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(entity.FileDownloadInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileUseCase_GetFileDownloadLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileDownloadLink'
type MockFileUseCase_GetFileDownloadLink_Call struct {
	*mock.Call
}

// GetFileDownloadLink is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockFileUseCase_Expecter) GetFileDownloadLink(ctx interface{}, fileID interface{}) *MockFileUseCase_GetFileDownloadLink_Call {
	return &MockFileUseCase_GetFileDownloadLink_Call{Call: _e.mock.On("GetFileDownloadLink", ctx, fileID)}
}

func (_c *MockFileUseCase_GetFileDownloadLink_Call) Run(run func(ctx context.Context, fileID string)) *MockFileUseCase_GetFileDownloadLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileUseCase_GetFileDownloadLink_Call) Return(fileDownloadInfo entity.FileDownloadInfo, err error) *MockFileUseCase_GetFileDownloadLink_Call {
	_c.Call.Return(fileDownloadInfo, err)
	return _c
}

func (_c *MockFileUseCase_GetFileDownloadLink_Call) RunAndReturn(run func(ctx context.Context, fileID string) (entity.FileDownloadInfo, error)) *MockFileUseCase_GetFileDownloadLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetS3FileList provides a mock function for the type MockFileUseCase
func (_mock *MockFileUseCase) GetS3FileList(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetS3FileList")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileUseCase_GetS3FileList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetS3FileList'
type MockFileUseCase_GetS3FileList_Call struct {
	*mock.Call
}

// GetS3FileList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFileUseCase_Expecter) GetS3FileList(ctx interface{}) *MockFileUseCase_GetS3FileList_Call {
	return &MockFileUseCase_GetS3FileList_Call{Call: _e.mock.On("GetS3FileList", ctx)}
}

func (_c *MockFileUseCase_GetS3FileList_Call) Run(run func(ctx context.Context)) *MockFileUseCase_GetS3FileList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileUseCase_GetS3FileList_Call) Return(strings []string, err error) *MockFileUseCase_GetS3FileList_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockFileUseCase_GetS3FileList_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockFileUseCase_GetS3FileList_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function for the type MockFileUseCase
func (_mock *MockFileUseCase) UploadFile(ctx context.Context, fileStream io.Reader, filename string, size int64, contentType string, baseKey string) (string, error) {
	ret := _mock.Called(ctx, fileStream, filename, size, contentType, baseKey)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, string, int64, string, string) (string, error)); ok {
		return returnFunc(ctx, fileStream, filename, size, contentType, baseKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, string, int64, string, string) string); ok {
		r0 = returnFunc(ctx, fileStream, filename, size, contentType, baseKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, string, int64, string, string) error); ok {
		r1 = returnFunc(ctx, fileStream, filename, size, contentType, baseKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileUseCase_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type MockFileUseCase_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - fileStream io.Reader
//   - filename string
//   - size int64
//   - contentType string
//   - baseKey string
func (_e *MockFileUseCase_Expecter) UploadFile(ctx interface{}, fileStream interface{}, filename interface{}, size interface{}, contentType interface{}, baseKey interface{}) *MockFileUseCase_UploadFile_Call {
	return &MockFileUseCase_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, fileStream, filename, size, contentType, baseKey)}
}

func (_c *MockFileUseCase_UploadFile_Call) Run(run func(ctx context.Context, fileStream io.Reader, filename string, size int64, contentType string, baseKey string)) *MockFileUseCase_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockFileUseCase_UploadFile_Call) Return(s string, err error) *MockFileUseCase_UploadFile_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileUseCase_UploadFile_Call) RunAndReturn(run func(ctx context.Context, fileStream io.Reader, filename string, size int64, contentType string, baseKey string) (string, error)) *MockFileUseCase_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}
