// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGreetingUseCase creates a new instance of MockGreetingUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGreetingUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGreetingUseCase {
	mock := &MockGreetingUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGreetingUseCase is an autogenerated mock type for the GreetingUseCase type
type MockGreetingUseCase struct {
	mock.Mock
}

type MockGreetingUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGreetingUseCase) EXPECT() *MockGreetingUseCase_Expecter {
	return &MockGreetingUseCase_Expecter{mock: &_m.Mock}
}

// GetGreetingMessage provides a mock function for the type MockGreetingUseCase
func (_mock *MockGreetingUseCase) GetGreetingMessage(ctx context.Context, name string) string {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetGreetingMessage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGreetingUseCase_GetGreetingMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGreetingMessage'
type MockGreetingUseCase_GetGreetingMessage_Call struct {
	*mock.Call
}

// GetGreetingMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockGreetingUseCase_Expecter) GetGreetingMessage(ctx interface{}, name interface{}) *MockGreetingUseCase_GetGreetingMessage_Call {
	return &MockGreetingUseCase_GetGreetingMessage_Call{Call: _e.mock.On("GetGreetingMessage", ctx, name)}
}

func (_c *MockGreetingUseCase_GetGreetingMessage_Call) Run(run func(ctx context.Context, name string)) *MockGreetingUseCase_GetGreetingMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGreetingUseCase_GetGreetingMessage_Call) Return(s string) *MockGreetingUseCase_GetGreetingMessage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGreetingUseCase_GetGreetingMessage_Call) RunAndReturn(run func(ctx context.Context, name string) string) *MockGreetingUseCase_GetGreetingMessage_Call {
	_c.Call.Return(run)
	return _c
}
