// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthUseCase creates a new instance of MockHealthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthUseCase {
	mock := &MockHealthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthUseCase is an autogenerated mock type for the HealthUseCase type
type MockHealthUseCase struct {
	mock.Mock
}

type MockHealthUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthUseCase) EXPECT() *MockHealthUseCase_Expecter {
	return &MockHealthUseCase_Expecter{mock: &_m.Mock}
}

// GetHealthStatus provides a mock function for the type MockHealthUseCase
func (_mock *MockHealthUseCase) GetHealthStatus(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetHealthStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHealthUseCase_GetHealthStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealthStatus'
type MockHealthUseCase_GetHealthStatus_Call struct {
	*mock.Call
}

// GetHealthStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthUseCase_Expecter) GetHealthStatus(ctx interface{}) *MockHealthUseCase_GetHealthStatus_Call {
	return &MockHealthUseCase_GetHealthStatus_Call{Call: _e.mock.On("GetHealthStatus", ctx)}
}

func (_c *MockHealthUseCase_GetHealthStatus_Call) Run(run func(ctx context.Context)) *MockHealthUseCase_GetHealthStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthUseCase_GetHealthStatus_Call) Return(s string, err error) *MockHealthUseCase_GetHealthStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHealthUseCase_GetHealthStatus_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockHealthUseCase_GetHealthStatus_Call {
	_c.Call.Return(run)
	return _c
}
