// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPetUseCase creates a new instance of MockPetUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPetUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPetUseCase {
	mock := &MockPetUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPetUseCase is an autogenerated mock type for the PetUseCase type
type MockPetUseCase struct {
	mock.Mock
}

type MockPetUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPetUseCase) EXPECT() *MockPetUseCase_Expecter {
	return &MockPetUseCase_Expecter{mock: &_m.Mock}
}

// GetAvailablePets provides a mock function for the type MockPetUseCase
func (_mock *MockPetUseCase) GetAvailablePets(ctx context.Context) ([]entity.Pet, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailablePets")
	}

	var r0 []entity.Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.Pet, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.Pet); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetUseCase_GetAvailablePets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailablePets'
type MockPetUseCase_GetAvailablePets_Call struct {
	*mock.Call
}

// GetAvailablePets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPetUseCase_Expecter) GetAvailablePets(ctx interface{}) *MockPetUseCase_GetAvailablePets_Call {
	return &MockPetUseCase_GetAvailablePets_Call{Call: _e.mock.On("GetAvailablePets", ctx)}
}

func (_c *MockPetUseCase_GetAvailablePets_Call) Run(run func(ctx context.Context)) *MockPetUseCase_GetAvailablePets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPetUseCase_GetAvailablePets_Call) Return(pets []entity.Pet, err error) *MockPetUseCase_GetAvailablePets_Call {
	_c.Call.Return(pets, err)
	return _c
}

func (_c *MockPetUseCase_GetAvailablePets_Call) RunAndReturn(run func(ctx context.Context) ([]entity.Pet, error)) *MockPetUseCase_GetAvailablePets_Call {
	_c.Call.Return(run)
	return _c
}

// GetPetByID provides a mock function for the type MockPetUseCase
func (_mock *MockPetUseCase) GetPetByID(ctx context.Context, id int64) (entity.Pet, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPetByID")
	}

	var r0 entity.Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (entity.Pet, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) entity.Pet); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Pet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetUseCase_GetPetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPetByID'
type MockPetUseCase_GetPetByID_Call struct {
	*mock.Call
}

// GetPetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockPetUseCase_Expecter) GetPetByID(ctx interface{}, id interface{}) *MockPetUseCase_GetPetByID_Call {
	return &MockPetUseCase_GetPetByID_Call{Call: _e.mock.On("GetPetByID", ctx, id)}
}

func (_c *MockPetUseCase_GetPetByID_Call) Run(run func(ctx context.Context, id int64)) *MockPetUseCase_GetPetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetUseCase_GetPetByID_Call) Return(pet entity.Pet, err error) *MockPetUseCase_GetPetByID_Call {
	_c.Call.Return(pet, err)
	return _c
}

func (_c *MockPetUseCase_GetPetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (entity.Pet, error)) *MockPetUseCase_GetPetByID_Call {
	_c.Call.Return(run)
	return _c
}
