// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReviewUseCase creates a new instance of MockReviewUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewUseCase {
	mock := &MockReviewUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewUseCase is an autogenerated mock type for the ReviewUseCase type
type MockReviewUseCase struct {
	mock.Mock
}

type MockReviewUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewUseCase) EXPECT() *MockReviewUseCase_Expecter {
	return &MockReviewUseCase_Expecter{mock: &_m.Mock}
}

// GetReviews provides a mock function for the type MockReviewUseCase
func (_mock *MockReviewUseCase) GetReviews(ctx context.Context, limit int64) ([]entity.Review, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetReviews")
	}

	var r0 []entity.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]entity.Review, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []entity.Review); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewUseCase_GetReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviews'
type MockReviewUseCase_GetReviews_Call struct {
	*mock.Call
}

// GetReviews is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
func (_e *MockReviewUseCase_Expecter) GetReviews(ctx interface{}, limit interface{}) *MockReviewUseCase_GetReviews_Call {
	return &MockReviewUseCase_GetReviews_Call{Call: _e.mock.On("GetReviews", ctx, limit)}
}

func (_c *MockReviewUseCase_GetReviews_Call) Run(run func(ctx context.Context, limit int64)) *MockReviewUseCase_GetReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewUseCase_GetReviews_Call) Return(reviews []entity.Review, err error) *MockReviewUseCase_GetReviews_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewUseCase_GetReviews_Call) RunAndReturn(run func(ctx context.Context, limit int64) ([]entity.Review, error)) *MockReviewUseCase_GetReviews_Call {
	_c.Call.Return(run)
	return _c
}

// PostReview provides a mock function for the type MockReviewUseCase
func (_mock *MockReviewUseCase) PostReview(ctx context.Context, review *entity.Review) error {
	ret := _mock.Called(ctx, review)

	if len(ret) == 0 {
		panic("no return value specified for PostReview")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Review) error); ok {
		r0 = returnFunc(ctx, review)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewUseCase_PostReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostReview'
type MockReviewUseCase_PostReview_Call struct {
	*mock.Call
}

// PostReview is a helper method to define mock.On call
//   - ctx context.Context
//   - review *entity.Review
func (_e *MockReviewUseCase_Expecter) PostReview(ctx interface{}, review interface{}) *MockReviewUseCase_PostReview_Call {
	return &MockReviewUseCase_PostReview_Call{Call: _e.mock.On("PostReview", ctx, review)}
}

func (_c *MockReviewUseCase_PostReview_Call) Run(run func(ctx context.Context, review *entity.Review)) *MockReviewUseCase_PostReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Review
		if args[1] != nil {
			arg1 = args[1].(*entity.Review)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewUseCase_PostReview_Call) Return(err error) *MockReviewUseCase_PostReview_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewUseCase_PostReview_Call) RunAndReturn(run func(ctx context.Context, review *entity.Review) error) *MockReviewUseCase_PostReview_Call {
	_c.Call.Return(run)
	return _c
}
