// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserUseCase creates a new instance of MockUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUseCase {
	mock := &MockUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserUseCase is an autogenerated mock type for the UserUseCase type
type MockUserUseCase struct {
	mock.Mock
}

type MockUserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUseCase) EXPECT() *MockUserUseCase_Expecter {
	return &MockUserUseCase_Expecter{mock: &_m.Mock}
}

// LoginUser provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) LoginUser(ctx context.Context, username string, password string) (string, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type MockUserUseCase_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockUserUseCase_Expecter) LoginUser(ctx interface{}, username interface{}, password interface{}) *MockUserUseCase_LoginUser_Call {
	return &MockUserUseCase_LoginUser_Call{Call: _e.mock.On("LoginUser", ctx, username, password)}
}

func (_c *MockUserUseCase_LoginUser_Call) Run(run func(ctx context.Context, username string, password string)) *MockUserUseCase_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserUseCase_LoginUser_Call) Return(s string, err error) *MockUserUseCase_LoginUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserUseCase_LoginUser_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (string, error)) *MockUserUseCase_LoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) RegisterUser(ctx context.Context, user *entity.User, password string) (string, error) {
	ret := _mock.Called(ctx, user, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User, string) (string, error)); ok {
		return returnFunc(ctx, user, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User, string) string); ok {
		r0 = returnFunc(ctx, user, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.User, string) error); ok {
		r1 = returnFunc(ctx, user, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockUserUseCase_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
//   - password string
func (_e *MockUserUseCase_Expecter) RegisterUser(ctx interface{}, user interface{}, password interface{}) *MockUserUseCase_RegisterUser_Call {
	return &MockUserUseCase_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, user, password)}
}

func (_c *MockUserUseCase_RegisterUser_Call) Run(run func(ctx context.Context, user *entity.User, password string)) *MockUserUseCase_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserUseCase_RegisterUser_Call) Return(s string, err error) *MockUserUseCase_RegisterUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserUseCase_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, user *entity.User, password string) (string, error)) *MockUserUseCase_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}
