// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/controller/restapi/schema"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookHandler creates a new instance of MockBookHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookHandler {
	mock := &MockBookHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookHandler is an autogenerated mock type for the BookHandler type
type MockBookHandler struct {
	mock.Mock
}

type MockBookHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookHandler) EXPECT() *MockBookHandler_Expecter {
	return &MockBookHandler_Expecter{mock: &_m.Mock}
}

// CreateBook provides a mock function for the type MockBookHandler
func (_mock *MockBookHandler) CreateBook(ctx context.Context, request *schema.CreateBookRequest) (*schema.CreateBookResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateBook")
	}

	var r0 *schema.CreateBookResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.CreateBookRequest) (*schema.CreateBookResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.CreateBookRequest) *schema.CreateBookResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.CreateBookResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.CreateBookRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookHandler_CreateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBook'
type MockBookHandler_CreateBook_Call struct {
	*mock.Call
}

// CreateBook is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.CreateBookRequest
func (_e *MockBookHandler_Expecter) CreateBook(ctx interface{}, request interface{}) *MockBookHandler_CreateBook_Call {
	return &MockBookHandler_CreateBook_Call{Call: _e.mock.On("CreateBook", ctx, request)}
}

func (_c *MockBookHandler_CreateBook_Call) Run(run func(ctx context.Context, request *schema.CreateBookRequest)) *MockBookHandler_CreateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.CreateBookRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.CreateBookRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookHandler_CreateBook_Call) Return(createBookResponse *schema.CreateBookResponse, err error) *MockBookHandler_CreateBook_Call {
	_c.Call.Return(createBookResponse, err)
	return _c
}

func (_c *MockBookHandler_CreateBook_Call) RunAndReturn(run func(ctx context.Context, request *schema.CreateBookRequest) (*schema.CreateBookResponse, error)) *MockBookHandler_CreateBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByID provides a mock function for the type MockBookHandler
func (_mock *MockBookHandler) GetBookByID(ctx context.Context, request *schema.GetBookByIDRequest) (*schema.GetBookByIDResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByID")
	}

	var r0 *schema.GetBookByIDResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetBookByIDRequest) (*schema.GetBookByIDResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetBookByIDRequest) *schema.GetBookByIDResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GetBookByIDResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GetBookByIDRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookHandler_GetBookByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByID'
type MockBookHandler_GetBookByID_Call struct {
	*mock.Call
}

// GetBookByID is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GetBookByIDRequest
func (_e *MockBookHandler_Expecter) GetBookByID(ctx interface{}, request interface{}) *MockBookHandler_GetBookByID_Call {
	return &MockBookHandler_GetBookByID_Call{Call: _e.mock.On("GetBookByID", ctx, request)}
}

func (_c *MockBookHandler_GetBookByID_Call) Run(run func(ctx context.Context, request *schema.GetBookByIDRequest)) *MockBookHandler_GetBookByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GetBookByIDRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GetBookByIDRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookHandler_GetBookByID_Call) Return(getBookByIDResponse *schema.GetBookByIDResponse, err error) *MockBookHandler_GetBookByID_Call {
	_c.Call.Return(getBookByIDResponse, err)
	return _c
}

func (_c *MockBookHandler_GetBookByID_Call) RunAndReturn(run func(ctx context.Context, request *schema.GetBookByIDRequest) (*schema.GetBookByIDResponse, error)) *MockBookHandler_GetBookByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooks provides a mock function for the type MockBookHandler
func (_mock *MockBookHandler) GetBooks(ctx context.Context, request *schema.GetBooksRequest) (*schema.GetBooksResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetBooks")
	}

	var r0 *schema.GetBooksResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetBooksRequest) (*schema.GetBooksResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetBooksRequest) *schema.GetBooksResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GetBooksResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GetBooksRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookHandler_GetBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooks'
type MockBookHandler_GetBooks_Call struct {
	*mock.Call
}

// GetBooks is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GetBooksRequest
func (_e *MockBookHandler_Expecter) GetBooks(ctx interface{}, request interface{}) *MockBookHandler_GetBooks_Call {
	return &MockBookHandler_GetBooks_Call{Call: _e.mock.On("GetBooks", ctx, request)}
}

func (_c *MockBookHandler_GetBooks_Call) Run(run func(ctx context.Context, request *schema.GetBooksRequest)) *MockBookHandler_GetBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GetBooksRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GetBooksRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookHandler_GetBooks_Call) Return(getBooksResponse *schema.GetBooksResponse, err error) *MockBookHandler_GetBooks_Call {
	_c.Call.Return(getBooksResponse, err)
	return _c
}

func (_c *MockBookHandler_GetBooks_Call) RunAndReturn(run func(ctx context.Context, request *schema.GetBooksRequest) (*schema.GetBooksResponse, error)) *MockBookHandler_GetBooks_Call {
	_c.Call.Return(run)
	return _c
}
