// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/controller/restapi/schema"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookPageHandler creates a new instance of MockBookPageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookPageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookPageHandler {
	mock := &MockBookPageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookPageHandler is an autogenerated mock type for the BookPageHandler type
type MockBookPageHandler struct {
	mock.Mock
}

type MockBookPageHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookPageHandler) EXPECT() *MockBookPageHandler_Expecter {
	return &MockBookPageHandler_Expecter{mock: &_m.Mock}
}

// CreateBookPage provides a mock function for the type MockBookPageHandler
func (_mock *MockBookPageHandler) CreateBookPage(ctx context.Context, request *schema.CreateBookPageRequest) (*schema.CreateBookPageResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateBookPage")
	}

	var r0 *schema.CreateBookPageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.CreateBookPageRequest) (*schema.CreateBookPageResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.CreateBookPageRequest) *schema.CreateBookPageResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.CreateBookPageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.CreateBookPageRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageHandler_CreateBookPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBookPage'
type MockBookPageHandler_CreateBookPage_Call struct {
	*mock.Call
}

// CreateBookPage is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.CreateBookPageRequest
func (_e *MockBookPageHandler_Expecter) CreateBookPage(ctx interface{}, request interface{}) *MockBookPageHandler_CreateBookPage_Call {
	return &MockBookPageHandler_CreateBookPage_Call{Call: _e.mock.On("CreateBookPage", ctx, request)}
}

func (_c *MockBookPageHandler_CreateBookPage_Call) Run(run func(ctx context.Context, request *schema.CreateBookPageRequest)) *MockBookPageHandler_CreateBookPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.CreateBookPageRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.CreateBookPageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookPageHandler_CreateBookPage_Call) Return(createBookPageResponse *schema.CreateBookPageResponse, err error) *MockBookPageHandler_CreateBookPage_Call {
	_c.Call.Return(createBookPageResponse, err)
	return _c
}

func (_c *MockBookPageHandler_CreateBookPage_Call) RunAndReturn(run func(ctx context.Context, request *schema.CreateBookPageRequest) (*schema.CreateBookPageResponse, error)) *MockBookPageHandler_CreateBookPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookPageByID provides a mock function for the type MockBookPageHandler
func (_mock *MockBookPageHandler) GetBookPageByID(ctx context.Context, request *schema.GetBookPageByIDRequest) (*schema.GetBookPageByIDResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetBookPageByID")
	}

	var r0 *schema.GetBookPageByIDResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetBookPageByIDRequest) (*schema.GetBookPageByIDResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetBookPageByIDRequest) *schema.GetBookPageByIDResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GetBookPageByIDResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GetBookPageByIDRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageHandler_GetBookPageByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookPageByID'
type MockBookPageHandler_GetBookPageByID_Call struct {
	*mock.Call
}

// GetBookPageByID is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GetBookPageByIDRequest
func (_e *MockBookPageHandler_Expecter) GetBookPageByID(ctx interface{}, request interface{}) *MockBookPageHandler_GetBookPageByID_Call {
	return &MockBookPageHandler_GetBookPageByID_Call{Call: _e.mock.On("GetBookPageByID", ctx, request)}
}

func (_c *MockBookPageHandler_GetBookPageByID_Call) Run(run func(ctx context.Context, request *schema.GetBookPageByIDRequest)) *MockBookPageHandler_GetBookPageByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GetBookPageByIDRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GetBookPageByIDRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookPageHandler_GetBookPageByID_Call) Return(getBookPageByIDResponse *schema.GetBookPageByIDResponse, err error) *MockBookPageHandler_GetBookPageByID_Call {
	_c.Call.Return(getBookPageByIDResponse, err)
	return _c
}

func (_c *MockBookPageHandler_GetBookPageByID_Call) RunAndReturn(run func(ctx context.Context, request *schema.GetBookPageByIDRequest) (*schema.GetBookPageByIDResponse, error)) *MockBookPageHandler_GetBookPageByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookPages provides a mock function for the type MockBookPageHandler
func (_mock *MockBookPageHandler) GetBookPages(ctx context.Context, request *schema.GetBookPagesRequest) (*schema.GetBookPagesResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetBookPages")
	}

	var r0 *schema.GetBookPagesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetBookPagesRequest) (*schema.GetBookPagesResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetBookPagesRequest) *schema.GetBookPagesResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GetBookPagesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GetBookPagesRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageHandler_GetBookPages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookPages'
type MockBookPageHandler_GetBookPages_Call struct {
	*mock.Call
}

// GetBookPages is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GetBookPagesRequest
func (_e *MockBookPageHandler_Expecter) GetBookPages(ctx interface{}, request interface{}) *MockBookPageHandler_GetBookPages_Call {
	return &MockBookPageHandler_GetBookPages_Call{Call: _e.mock.On("GetBookPages", ctx, request)}
}

func (_c *MockBookPageHandler_GetBookPages_Call) Run(run func(ctx context.Context, request *schema.GetBookPagesRequest)) *MockBookPageHandler_GetBookPages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GetBookPagesRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GetBookPagesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookPageHandler_GetBookPages_Call) Return(getBookPagesResponse *schema.GetBookPagesResponse, err error) *MockBookPageHandler_GetBookPages_Call {
	_c.Call.Return(getBookPagesResponse, err)
	return _c
}

func (_c *MockBookPageHandler_GetBookPages_Call) RunAndReturn(run func(ctx context.Context, request *schema.GetBookPagesRequest) (*schema.GetBookPagesResponse, error)) *MockBookPageHandler_GetBookPages_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookPagesByOffset provides a mock function for the type MockBookPageHandler
func (_mock *MockBookPageHandler) GetBookPagesByOffset(ctx context.Context, request *schema.GetBookPagesOffsetRequest) (*schema.GetBookPagesResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetBookPagesByOffset")
	}

	var r0 *schema.GetBookPagesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetBookPagesOffsetRequest) (*schema.GetBookPagesResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetBookPagesOffsetRequest) *schema.GetBookPagesResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GetBookPagesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GetBookPagesOffsetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageHandler_GetBookPagesByOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookPagesByOffset'
type MockBookPageHandler_GetBookPagesByOffset_Call struct {
	*mock.Call
}

// GetBookPagesByOffset is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GetBookPagesOffsetRequest
func (_e *MockBookPageHandler_Expecter) GetBookPagesByOffset(ctx interface{}, request interface{}) *MockBookPageHandler_GetBookPagesByOffset_Call {
	return &MockBookPageHandler_GetBookPagesByOffset_Call{Call: _e.mock.On("GetBookPagesByOffset", ctx, request)}
}

func (_c *MockBookPageHandler_GetBookPagesByOffset_Call) Run(run func(ctx context.Context, request *schema.GetBookPagesOffsetRequest)) *MockBookPageHandler_GetBookPagesByOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GetBookPagesOffsetRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GetBookPagesOffsetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookPageHandler_GetBookPagesByOffset_Call) Return(getBookPagesResponse *schema.GetBookPagesResponse, err error) *MockBookPageHandler_GetBookPagesByOffset_Call {
	_c.Call.Return(getBookPagesResponse, err)
	return _c
}

func (_c *MockBookPageHandler_GetBookPagesByOffset_Call) RunAndReturn(run func(ctx context.Context, request *schema.GetBookPagesOffsetRequest) (*schema.GetBookPagesResponse, error)) *MockBookPageHandler_GetBookPagesByOffset_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookPagesByRange provides a mock function for the type MockBookPageHandler
func (_mock *MockBookPageHandler) GetBookPagesByRange(ctx context.Context, request *schema.GetBookPagesRangeRequest) (*schema.GetBookPagesResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetBookPagesByRange")
	}

	var r0 *schema.GetBookPagesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetBookPagesRangeRequest) (*schema.GetBookPagesResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetBookPagesRangeRequest) *schema.GetBookPagesResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GetBookPagesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GetBookPagesRangeRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookPageHandler_GetBookPagesByRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookPagesByRange'
type MockBookPageHandler_GetBookPagesByRange_Call struct {
	*mock.Call
}

// GetBookPagesByRange is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GetBookPagesRangeRequest
func (_e *MockBookPageHandler_Expecter) GetBookPagesByRange(ctx interface{}, request interface{}) *MockBookPageHandler_GetBookPagesByRange_Call {
	return &MockBookPageHandler_GetBookPagesByRange_Call{Call: _e.mock.On("GetBookPagesByRange", ctx, request)}
}

func (_c *MockBookPageHandler_GetBookPagesByRange_Call) Run(run func(ctx context.Context, request *schema.GetBookPagesRangeRequest)) *MockBookPageHandler_GetBookPagesByRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GetBookPagesRangeRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GetBookPagesRangeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookPageHandler_GetBookPagesByRange_Call) Return(getBookPagesResponse *schema.GetBookPagesResponse, err error) *MockBookPageHandler_GetBookPagesByRange_Call {
	_c.Call.Return(getBookPagesResponse, err)
	return _c
}

func (_c *MockBookPageHandler_GetBookPagesByRange_Call) RunAndReturn(run func(ctx context.Context, request *schema.GetBookPagesRangeRequest) (*schema.GetBookPagesResponse, error)) *MockBookPageHandler_GetBookPagesByRange_Call {
	_c.Call.Return(run)
	return _c
}
