// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/controller/restapi/schema"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileHandler creates a new instance of MockFileHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileHandler {
	mock := &MockFileHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileHandler is an autogenerated mock type for the FileHandler type
type MockFileHandler struct {
	mock.Mock
}

type MockFileHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileHandler) EXPECT() *MockFileHandler_Expecter {
	return &MockFileHandler_Expecter{mock: &_m.Mock}
}

// GetFileDownloadLink provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) GetFileDownloadLink(ctx context.Context, request *schema.GetFileDownloadLinkRequest) (*schema.GetFileDownloadLinkResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetFileDownloadLink")
	}

	var r0 *schema.GetFileDownloadLinkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetFileDownloadLinkRequest) (*schema.GetFileDownloadLinkResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetFileDownloadLinkRequest) *schema.GetFileDownloadLinkResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GetFileDownloadLinkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GetFileDownloadLinkRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileHandler_GetFileDownloadLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileDownloadLink'
type MockFileHandler_GetFileDownloadLink_Call struct {
	*mock.Call
}

// GetFileDownloadLink is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GetFileDownloadLinkRequest
func (_e *MockFileHandler_Expecter) GetFileDownloadLink(ctx interface{}, request interface{}) *MockFileHandler_GetFileDownloadLink_Call {
	return &MockFileHandler_GetFileDownloadLink_Call{Call: _e.mock.On("GetFileDownloadLink", ctx, request)}
}

func (_c *MockFileHandler_GetFileDownloadLink_Call) Run(run func(ctx context.Context, request *schema.GetFileDownloadLinkRequest)) *MockFileHandler_GetFileDownloadLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GetFileDownloadLinkRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GetFileDownloadLinkRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileHandler_GetFileDownloadLink_Call) Return(getFileDownloadLinkResponse *schema.GetFileDownloadLinkResponse, err error) *MockFileHandler_GetFileDownloadLink_Call {
	_c.Call.Return(getFileDownloadLinkResponse, err)
	return _c
}

func (_c *MockFileHandler_GetFileDownloadLink_Call) RunAndReturn(run func(ctx context.Context, request *schema.GetFileDownloadLinkRequest) (*schema.GetFileDownloadLinkResponse, error)) *MockFileHandler_GetFileDownloadLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetS3FileList provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) GetS3FileList(ctx context.Context, request *schema.GetS3FileListRequest) (*schema.GetS3FileListResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetS3FileList")
	}

	var r0 *schema.GetS3FileListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetS3FileListRequest) (*schema.GetS3FileListResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetS3FileListRequest) *schema.GetS3FileListResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GetS3FileListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GetS3FileListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileHandler_GetS3FileList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetS3FileList'
type MockFileHandler_GetS3FileList_Call struct {
	*mock.Call
}

// GetS3FileList is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GetS3FileListRequest
func (_e *MockFileHandler_Expecter) GetS3FileList(ctx interface{}, request interface{}) *MockFileHandler_GetS3FileList_Call {
	return &MockFileHandler_GetS3FileList_Call{Call: _e.mock.On("GetS3FileList", ctx, request)}
}

func (_c *MockFileHandler_GetS3FileList_Call) Run(run func(ctx context.Context, request *schema.GetS3FileListRequest)) *MockFileHandler_GetS3FileList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GetS3FileListRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GetS3FileListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileHandler_GetS3FileList_Call) Return(getS3FileListResponse *schema.GetS3FileListResponse, err error) *MockFileHandler_GetS3FileList_Call {
	_c.Call.Return(getS3FileListResponse, err)
	return _c
}

func (_c *MockFileHandler_GetS3FileList_Call) RunAndReturn(run func(ctx context.Context, request *schema.GetS3FileListRequest) (*schema.GetS3FileListResponse, error)) *MockFileHandler_GetS3FileList_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) UploadFile(ctx context.Context, request *schema.UploadFileRequest) (*schema.UploadFileResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 *schema.UploadFileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.UploadFileRequest) (*schema.UploadFileResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.UploadFileRequest) *schema.UploadFileResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.UploadFileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.UploadFileRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileHandler_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type MockFileHandler_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.UploadFileRequest
func (_e *MockFileHandler_Expecter) UploadFile(ctx interface{}, request interface{}) *MockFileHandler_UploadFile_Call {
	return &MockFileHandler_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, request)}
}

func (_c *MockFileHandler_UploadFile_Call) Run(run func(ctx context.Context, request *schema.UploadFileRequest)) *MockFileHandler_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.UploadFileRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.UploadFileRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileHandler_UploadFile_Call) Return(uploadFileResponse *schema.UploadFileResponse, err error) *MockFileHandler_UploadFile_Call {
	_c.Call.Return(uploadFileResponse, err)
	return _c
}

func (_c *MockFileHandler_UploadFile_Call) RunAndReturn(run func(ctx context.Context, request *schema.UploadFileRequest) (*schema.UploadFileResponse, error)) *MockFileHandler_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}
