// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/controller/restapi/schema"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGreetingHandler creates a new instance of MockGreetingHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGreetingHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGreetingHandler {
	mock := &MockGreetingHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGreetingHandler is an autogenerated mock type for the GreetingHandler type
type MockGreetingHandler struct {
	mock.Mock
}

type MockGreetingHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGreetingHandler) EXPECT() *MockGreetingHandler_Expecter {
	return &MockGreetingHandler_Expecter{mock: &_m.Mock}
}

// GetGreeting provides a mock function for the type MockGreetingHandler
func (_mock *MockGreetingHandler) GetGreeting(ctx context.Context, request *schema.GreetingRequest) (*schema.GreetingResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetGreeting")
	}

	var r0 *schema.GreetingResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GreetingRequest) (*schema.GreetingResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GreetingRequest) *schema.GreetingResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GreetingResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GreetingRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGreetingHandler_GetGreeting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGreeting'
type MockGreetingHandler_GetGreeting_Call struct {
	*mock.Call
}

// GetGreeting is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GreetingRequest
func (_e *MockGreetingHandler_Expecter) GetGreeting(ctx interface{}, request interface{}) *MockGreetingHandler_GetGreeting_Call {
	return &MockGreetingHandler_GetGreeting_Call{Call: _e.mock.On("GetGreeting", ctx, request)}
}

func (_c *MockGreetingHandler_GetGreeting_Call) Run(run func(ctx context.Context, request *schema.GreetingRequest)) *MockGreetingHandler_GetGreeting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GreetingRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GreetingRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGreetingHandler_GetGreeting_Call) Return(greetingResponse *schema.GreetingResponse, err error) *MockGreetingHandler_GetGreeting_Call {
	_c.Call.Return(greetingResponse, err)
	return _c
}

func (_c *MockGreetingHandler_GetGreeting_Call) RunAndReturn(run func(ctx context.Context, request *schema.GreetingRequest) (*schema.GreetingResponse, error)) *MockGreetingHandler_GetGreeting_Call {
	_c.Call.Return(run)
	return _c
}
