// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/controller/restapi/schema"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthHandler creates a new instance of MockHealthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthHandler {
	mock := &MockHealthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthHandler is an autogenerated mock type for the HealthHandler type
type MockHealthHandler struct {
	mock.Mock
}

type MockHealthHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthHandler) EXPECT() *MockHealthHandler_Expecter {
	return &MockHealthHandler_Expecter{mock: &_m.Mock}
}

// GetHealthStatus provides a mock function for the type MockHealthHandler
func (_mock *MockHealthHandler) GetHealthStatus(ctx context.Context, request *schema.GetHealthStatusRequest) (*schema.GetHealthStatusResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetHealthStatus")
	}

	var r0 *schema.GetHealthStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetHealthStatusRequest) (*schema.GetHealthStatusResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetHealthStatusRequest) *schema.GetHealthStatusResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GetHealthStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GetHealthStatusRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHealthHandler_GetHealthStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealthStatus'
type MockHealthHandler_GetHealthStatus_Call struct {
	*mock.Call
}

// GetHealthStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GetHealthStatusRequest
func (_e *MockHealthHandler_Expecter) GetHealthStatus(ctx interface{}, request interface{}) *MockHealthHandler_GetHealthStatus_Call {
	return &MockHealthHandler_GetHealthStatus_Call{Call: _e.mock.On("GetHealthStatus", ctx, request)}
}

func (_c *MockHealthHandler_GetHealthStatus_Call) Run(run func(ctx context.Context, request *schema.GetHealthStatusRequest)) *MockHealthHandler_GetHealthStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GetHealthStatusRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GetHealthStatusRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHealthHandler_GetHealthStatus_Call) Return(getHealthStatusResponse *schema.GetHealthStatusResponse, err error) *MockHealthHandler_GetHealthStatus_Call {
	_c.Call.Return(getHealthStatusResponse, err)
	return _c
}

func (_c *MockHealthHandler_GetHealthStatus_Call) RunAndReturn(run func(ctx context.Context, request *schema.GetHealthStatusRequest) (*schema.GetHealthStatusResponse, error)) *MockHealthHandler_GetHealthStatus_Call {
	_c.Call.Return(run)
	return _c
}
