// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/controller/restapi/schema"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPetHandler creates a new instance of MockPetHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPetHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPetHandler {
	mock := &MockPetHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPetHandler is an autogenerated mock type for the PetHandler type
type MockPetHandler struct {
	mock.Mock
}

type MockPetHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPetHandler) EXPECT() *MockPetHandler_Expecter {
	return &MockPetHandler_Expecter{mock: &_m.Mock}
}

// GetAvailablePets provides a mock function for the type MockPetHandler
func (_mock *MockPetHandler) GetAvailablePets(ctx context.Context, request *schema.GetAvailablePetsRequest) (*schema.GetAvailablePetsResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailablePets")
	}

	var r0 *schema.GetAvailablePetsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetAvailablePetsRequest) (*schema.GetAvailablePetsResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetAvailablePetsRequest) *schema.GetAvailablePetsResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GetAvailablePetsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GetAvailablePetsRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetHandler_GetAvailablePets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailablePets'
type MockPetHandler_GetAvailablePets_Call struct {
	*mock.Call
}

// GetAvailablePets is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GetAvailablePetsRequest
func (_e *MockPetHandler_Expecter) GetAvailablePets(ctx interface{}, request interface{}) *MockPetHandler_GetAvailablePets_Call {
	return &MockPetHandler_GetAvailablePets_Call{Call: _e.mock.On("GetAvailablePets", ctx, request)}
}

func (_c *MockPetHandler_GetAvailablePets_Call) Run(run func(ctx context.Context, request *schema.GetAvailablePetsRequest)) *MockPetHandler_GetAvailablePets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GetAvailablePetsRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GetAvailablePetsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetHandler_GetAvailablePets_Call) Return(getAvailablePetsResponse *schema.GetAvailablePetsResponse, err error) *MockPetHandler_GetAvailablePets_Call {
	_c.Call.Return(getAvailablePetsResponse, err)
	return _c
}

func (_c *MockPetHandler_GetAvailablePets_Call) RunAndReturn(run func(ctx context.Context, request *schema.GetAvailablePetsRequest) (*schema.GetAvailablePetsResponse, error)) *MockPetHandler_GetAvailablePets_Call {
	_c.Call.Return(run)
	return _c
}

// GetPetByID provides a mock function for the type MockPetHandler
func (_mock *MockPetHandler) GetPetByID(ctx context.Context, request *schema.GetPetByIDRequest) (*schema.GetPetByIDResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetPetByID")
	}

	var r0 *schema.GetPetByIDResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetPetByIDRequest) (*schema.GetPetByIDResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetPetByIDRequest) *schema.GetPetByIDResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GetPetByIDResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GetPetByIDRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetHandler_GetPetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPetByID'
type MockPetHandler_GetPetByID_Call struct {
	*mock.Call
}

// GetPetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GetPetByIDRequest
func (_e *MockPetHandler_Expecter) GetPetByID(ctx interface{}, request interface{}) *MockPetHandler_GetPetByID_Call {
	return &MockPetHandler_GetPetByID_Call{Call: _e.mock.On("GetPetByID", ctx, request)}
}

func (_c *MockPetHandler_GetPetByID_Call) Run(run func(ctx context.Context, request *schema.GetPetByIDRequest)) *MockPetHandler_GetPetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GetPetByIDRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GetPetByIDRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetHandler_GetPetByID_Call) Return(getPetByIDResponse *schema.GetPetByIDResponse, err error) *MockPetHandler_GetPetByID_Call {
	_c.Call.Return(getPetByIDResponse, err)
	return _c
}

func (_c *MockPetHandler_GetPetByID_Call) RunAndReturn(run func(ctx context.Context, request *schema.GetPetByIDRequest) (*schema.GetPetByIDResponse, error)) *MockPetHandler_GetPetByID_Call {
	_c.Call.Return(run)
	return _c
}
