// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/controller/restapi/schema"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReviewHandler creates a new instance of MockReviewHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewHandler {
	mock := &MockReviewHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewHandler is an autogenerated mock type for the ReviewHandler type
type MockReviewHandler struct {
	mock.Mock
}

type MockReviewHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewHandler) EXPECT() *MockReviewHandler_Expecter {
	return &MockReviewHandler_Expecter{mock: &_m.Mock}
}

// CreateReview provides a mock function for the type MockReviewHandler
func (_mock *MockReviewHandler) CreateReview(ctx context.Context, request *schema.CreateReviewRequest) (*schema.CreateReviewResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateReview")
	}

	var r0 *schema.CreateReviewResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.CreateReviewRequest) (*schema.CreateReviewResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.CreateReviewRequest) *schema.CreateReviewResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.CreateReviewResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.CreateReviewRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewHandler_CreateReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReview'
type MockReviewHandler_CreateReview_Call struct {
	*mock.Call
}

// CreateReview is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.CreateReviewRequest
func (_e *MockReviewHandler_Expecter) CreateReview(ctx interface{}, request interface{}) *MockReviewHandler_CreateReview_Call {
	return &MockReviewHandler_CreateReview_Call{Call: _e.mock.On("CreateReview", ctx, request)}
}

func (_c *MockReviewHandler_CreateReview_Call) Run(run func(ctx context.Context, request *schema.CreateReviewRequest)) *MockReviewHandler_CreateReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.CreateReviewRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.CreateReviewRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewHandler_CreateReview_Call) Return(createReviewResponse *schema.CreateReviewResponse, err error) *MockReviewHandler_CreateReview_Call {
	_c.Call.Return(createReviewResponse, err)
	return _c
}

func (_c *MockReviewHandler_CreateReview_Call) RunAndReturn(run func(ctx context.Context, request *schema.CreateReviewRequest) (*schema.CreateReviewResponse, error)) *MockReviewHandler_CreateReview_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviews provides a mock function for the type MockReviewHandler
func (_mock *MockReviewHandler) GetReviews(ctx context.Context, request *schema.GetReviewsRequest) (*schema.GetReviewsResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetReviews")
	}

	var r0 *schema.GetReviewsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetReviewsRequest) (*schema.GetReviewsResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.GetReviewsRequest) *schema.GetReviewsResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.GetReviewsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.GetReviewsRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewHandler_GetReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviews'
type MockReviewHandler_GetReviews_Call struct {
	*mock.Call
}

// GetReviews is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.GetReviewsRequest
func (_e *MockReviewHandler_Expecter) GetReviews(ctx interface{}, request interface{}) *MockReviewHandler_GetReviews_Call {
	return &MockReviewHandler_GetReviews_Call{Call: _e.mock.On("GetReviews", ctx, request)}
}

func (_c *MockReviewHandler_GetReviews_Call) Run(run func(ctx context.Context, request *schema.GetReviewsRequest)) *MockReviewHandler_GetReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.GetReviewsRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.GetReviewsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewHandler_GetReviews_Call) Return(getReviewsResponse *schema.GetReviewsResponse, err error) *MockReviewHandler_GetReviews_Call {
	_c.Call.Return(getReviewsResponse, err)
	return _c
}

func (_c *MockReviewHandler_GetReviews_Call) RunAndReturn(run func(ctx context.Context, request *schema.GetReviewsRequest) (*schema.GetReviewsResponse, error)) *MockReviewHandler_GetReviews_Call {
	_c.Call.Return(run)
	return _c
}
