// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/junior-meowmeow/go-echo-huma-rest-api/internal/controller/restapi/schema"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserHandler creates a new instance of MockUserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserHandler {
	mock := &MockUserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserHandler is an autogenerated mock type for the UserHandler type
type MockUserHandler struct {
	mock.Mock
}

type MockUserHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserHandler) EXPECT() *MockUserHandler_Expecter {
	return &MockUserHandler_Expecter{mock: &_m.Mock}
}

// LoginUser provides a mock function for the type MockUserHandler
func (_mock *MockUserHandler) LoginUser(ctx context.Context, request *schema.LoginUserRequest) (*schema.LoginUserResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 *schema.LoginUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.LoginUserRequest) (*schema.LoginUserResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.LoginUserRequest) *schema.LoginUserResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.LoginUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.LoginUserRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHandler_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type MockUserHandler_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.LoginUserRequest
func (_e *MockUserHandler_Expecter) LoginUser(ctx interface{}, request interface{}) *MockUserHandler_LoginUser_Call {
	return &MockUserHandler_LoginUser_Call{Call: _e.mock.On("LoginUser", ctx, request)}
}

func (_c *MockUserHandler_LoginUser_Call) Run(run func(ctx context.Context, request *schema.LoginUserRequest)) *MockUserHandler_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.LoginUserRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.LoginUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserHandler_LoginUser_Call) Return(loginUserResponse *schema.LoginUserResponse, err error) *MockUserHandler_LoginUser_Call {
	_c.Call.Return(loginUserResponse, err)
	return _c
}

func (_c *MockUserHandler_LoginUser_Call) RunAndReturn(run func(ctx context.Context, request *schema.LoginUserRequest) (*schema.LoginUserResponse, error)) *MockUserHandler_LoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function for the type MockUserHandler
func (_mock *MockUserHandler) RegisterUser(ctx context.Context, request *schema.RegisterUserRequest) (*schema.RegisterUserResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *schema.RegisterUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.RegisterUserRequest) (*schema.RegisterUserResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *schema.RegisterUserRequest) *schema.RegisterUserResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.RegisterUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *schema.RegisterUserRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHandler_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockUserHandler_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - request *schema.RegisterUserRequest
func (_e *MockUserHandler_Expecter) RegisterUser(ctx interface{}, request interface{}) *MockUserHandler_RegisterUser_Call {
	return &MockUserHandler_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, request)}
}

func (_c *MockUserHandler_RegisterUser_Call) Run(run func(ctx context.Context, request *schema.RegisterUserRequest)) *MockUserHandler_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *schema.RegisterUserRequest
		if args[1] != nil {
			arg1 = args[1].(*schema.RegisterUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserHandler_RegisterUser_Call) Return(registerUserResponse *schema.RegisterUserResponse, err error) *MockUserHandler_RegisterUser_Call {
	_c.Call.Return(registerUserResponse, err)
	return _c
}

func (_c *MockUserHandler_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, request *schema.RegisterUserRequest) (*schema.RegisterUserResponse, error)) *MockUserHandler_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}
