// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: book.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBook = `-- name: CreateBook :exec
INSERT INTO books (
    id, name, description, author, isbn, genre, cover_image_file_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateBookParams struct {
	ID               uuid.UUID
	Name             string
	Description      string
	Author           string
	Isbn             string
	Genre            string
	CoverImageFileID string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) error {
	_, err := q.db.Exec(ctx, createBook,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Author,
		arg.Isbn,
		arg.Genre,
		arg.CoverImageFileID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getAllBooks = `-- name: GetAllBooks :many
SELECT id, name, description, author, isbn, genre, cover_image_file_id, created_at, updated_at FROM books 
ORDER BY created_at DESC
`

func (q *Queries) GetAllBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, getAllBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Author,
			&i.Isbn,
			&i.Genre,
			&i.CoverImageFileID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, name, description, author, isbn, genre, cover_image_file_id, created_at, updated_at FROM books 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBookByID(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Author,
		&i.Isbn,
		&i.Genre,
		&i.CoverImageFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooksWithPagination = `-- name: GetBooksWithPagination :many
SELECT id, name, description, author, isbn, genre, cover_image_file_id, created_at, updated_at FROM books 
ORDER BY created_at DESC 
LIMIT $1 OFFSET $2
`

type GetBooksWithPaginationParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetBooksWithPagination(ctx context.Context, arg GetBooksWithPaginationParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, getBooksWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Author,
			&i.Isbn,
			&i.Genre,
			&i.CoverImageFileID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
