// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID               uuid.UUID
	Name             string
	Description      string
	Author           string
	Isbn             string
	Genre            string
	CoverImageFileID string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type BookPage struct {
	ID                  uuid.UUID
	BookID              uuid.UUID
	PageNumber          int64
	Content             string
	IsBookmarked        bool
	Highlight           string
	AttachedImageFileID string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}
