name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-api-docs:
    name: Check API documents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Verify generated docs
        run: |
          go run ./cmd/gen-docs
          git diff --exit-code || (echo "OpenAPI documents are outdated." && exit 1)

  check-gen-codes:
    name: Check generated codes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Setup sqlc
        uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.31.1'
      - name: Verify sqlc generated code
        run: sqlc diff
      - name: Install mockery
        run: go install github.com/vektra/mockery/v3@v3.7.0
      - name: Verify generated mocks
        run: |
          make mock-gen
          git diff --exit-code || (echo "Generated mocks are outdated." && exit 1)

  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
          args: --timeout=10m

  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Build
        run: go build -v ./...
      - name: Run tests
        run: go test ./... -v -cover | tee raw_test_output.log
      - name: Convert results to JSON
        if: always() 
        run: go tool test2json < raw_test_output.log > TestResults.json
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: Go-test-results
          path: TestResults.json

  vulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.25.8
           go-package: ./...
