// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: book_page.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBookPage = `-- name: CreateBookPage :exec
INSERT INTO book_pages (
    id, book_id, page_number, content, is_bookmarked, highlight, attached_image_file_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateBookPageParams struct {
	ID                  uuid.UUID
	BookID              uuid.UUID
	PageNumber          int64
	Content             string
	IsBookmarked        bool
	Highlight           string
	AttachedImageFileID string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) CreateBookPage(ctx context.Context, arg CreateBookPageParams) error {
	_, err := q.db.Exec(ctx, createBookPage,
		arg.ID,
		arg.BookID,
		arg.PageNumber,
		arg.Content,
		arg.IsBookmarked,
		arg.Highlight,
		arg.AttachedImageFileID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getBookPageByID = `-- name: GetBookPageByID :one
SELECT id, book_id, page_number, content, is_bookmarked, highlight, attached_image_file_id, created_at, updated_at FROM book_pages 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBookPageByID(ctx context.Context, id uuid.UUID) (BookPage, error) {
	row := q.db.QueryRow(ctx, getBookPageByID, id)
	var i BookPage
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.PageNumber,
		&i.Content,
		&i.IsBookmarked,
		&i.Highlight,
		&i.AttachedImageFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookPagesByBookID = `-- name: GetBookPagesByBookID :many
SELECT id, book_id, page_number, content, is_bookmarked, highlight, attached_image_file_id, created_at, updated_at FROM book_pages 
WHERE book_id = $1 
ORDER BY page_number ASC
`

func (q *Queries) GetBookPagesByBookID(ctx context.Context, bookID uuid.UUID) ([]BookPage, error) {
	rows, err := q.db.Query(ctx, getBookPagesByBookID, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookPage
	for rows.Next() {
		var i BookPage
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.PageNumber,
			&i.Content,
			&i.IsBookmarked,
			&i.Highlight,
			&i.AttachedImageFileID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookpagesByBookIDWithPagination = `-- name: GetBookpagesByBookIDWithPagination :many
SELECT id, book_id, page_number, content, is_bookmarked, highlight, attached_image_file_id, created_at, updated_at FROM book_pages 
WHERE book_id = $1 
ORDER BY page_number ASC 
LIMIT $2 OFFSET $3
`

type GetBookpagesByBookIDWithPaginationParams struct {
	BookID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetBookpagesByBookIDWithPagination(ctx context.Context, arg GetBookpagesByBookIDWithPaginationParams) ([]BookPage, error) {
	rows, err := q.db.Query(ctx, getBookpagesByBookIDWithPagination, arg.BookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookPage
	for rows.Next() {
		var i BookPage
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.PageNumber,
			&i.Content,
			&i.IsBookmarked,
			&i.Highlight,
			&i.AttachedImageFileID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookpagesByPageRange = `-- name: GetBookpagesByPageRange :many
SELECT id, book_id, page_number, content, is_bookmarked, highlight, attached_image_file_id, created_at, updated_at FROM book_pages 
WHERE book_id = $1 AND page_number >= $2 AND page_number <= $3
ORDER BY page_number ASC
`

type GetBookpagesByPageRangeParams struct {
	BookID       uuid.UUID
	PageNumber   int64
	PageNumber_2 int64
}

func (q *Queries) GetBookpagesByPageRange(ctx context.Context, arg GetBookpagesByPageRangeParams) ([]BookPage, error) {
	rows, err := q.db.Query(ctx, getBookpagesByPageRange, arg.BookID, arg.PageNumber, arg.PageNumber_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookPage
	for rows.Next() {
		var i BookPage
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.PageNumber,
			&i.Content,
			&i.IsBookmarked,
			&i.Highlight,
			&i.AttachedImageFileID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
